### ISSUE TITLE
Certain Malformed references are accepted and produce weird results

### ISSUE THREAD

**Issue by whurdwfd** [navigo-app/bible-ref-parser-lib#5]
I ran into a weird one:

```shell
matt3 13 17
```

This was the title of an image, ostensibly for Matthew chapters 3, 13, and 17. The parser returned this:

```
4031317001-4031317999
```

I'm not sure what I would have expected this to parse to. Or if it's really even valid at all.

**Comment by jamesbnance** [comment]
Because the parser removes spaces, and then treats the first number before a colon like a chapter, this is being interpreted as Matthew, chapter 31317

**Comment by jamesbnance** [comment]
@whurdwfd 
The changes I have made are all we can do on our end, I think.
